# Generated by Django 3.0.2 on 2020-03-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='id',
        ),
        migrations.AddField(
            model_name='storage',
            name='key',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
