# Generated by Django 3.0.2 on 2020-03-20 16:58

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20200320_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='key',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storage',
            name='list_words',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
