# Generated by Django 3.0.2 on 2020-03-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_auto_20200320_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='list_words',
            field=models.CharField(max_length=100),
        ),
    ]
